---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: default
  image: rancher/dapper:v0.6.0
  environment:
    KEY:
      from_secret: _key
  commands:
    - 'if [ -z "$KEY" ]; then echo "Secret not set"; else echo "Secret is set"; fi'
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
    exclude:
    - tag

- name: build
  pull: default
  image: rancher/dapper:v0.6.0
  commands:
  - BUILD_LATEST=true dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
      - tag

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/static/latest2
    target: releases.rancher.com/ui/latest2
    token:
      from_secret: google_auth_key
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
      - tag

- name: build-release
  pull: default
  image: rancher/dapper:v0.6.0
  commands:
  - dapper ci
  environment:
    ENVIRONMENT: production
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
      - tag
    ref:
      include:
      - "refs/tags/v2.8.*"


- name: upload-release
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/static/${DRONE_TAG##v}
    target: releases.rancher.com/ui/${DRONE_TAG##v}
    token:
      from_secret: google_auth_key
  when:
    event:
      - tag
    ref:
      include:
      - "refs/tags/v2.8.*"

- name: upload-release-tar
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/static/${DRONE_TAG##v}.tar.gz
    target: releases.rancher.com/ui/${DRONE_TAG##v}.tar.gz
    token:
      from_secret: google_auth_key
  when:
    event:
      - tag
    ref:
      include:
      - "refs/tags/v2.8.*"

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: fossa

steps:
- name: fossa
  image: rancher/drone-fossa:latest
  failure: ignore
  settings:
    api_key:
      from_secret: FOSSA_API_KEY
    when:
      instance:
        - drone-publish.rancher.io
